import './globals.css';
import type { Metadata } from 'next';
import Header from './_components/header';
import Footer from './_components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="relative">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
