import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './_components/header';
import Footer from './_components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative min-h-screen`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
